name: GitHub Actions Demo
on: [push]
jobs:
  Test:
    runs-on: macos-12
    steps:
      - name: Install go...
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"
      - run: go version
      - name: Checkout repo...
        uses: actions/checkout@v3
      - name: Run Tests...
        run: go test -v ./saml/
      - run: go build -o aws-login .