name: new feature
on:
  pull_request:
jobs:
  Test:
    runs-on: macos-12
    steps:
      - name: Install go...
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"
      - name: Checkout repo...
        uses: actions/checkout@v3
      - name: Run Tests...
        run: |
          go test -v ./saml/
          go test -v ./auth/
  
  Test-Windows:
    runs-on: windows-latest
    steps:
      - name: Install go...
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"
      - name: Checkout repo...
        uses: actions/checkout@v3
      - name: Run Tests...
        run: |
          go test -v ./saml/
          go test -v ./auth/

  Build:
    runs-on: macos-12
    needs:
      - Test
    steps:
      - name: Install go...
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"
      - name: Checkout repo...
        uses: actions/checkout@v3
      - name: Test building the binary...
        run: go build -o aws-login .
      - run: ./aws-login version
  
  Build-Windows:
    runs-on: windows-latest
    needs:
      - Test
    steps:
      - name: Install go...
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.1"
      - name: Checkout repo...
        uses: actions/checkout@v3
      - name: Test building the binary...
        run: go build -o aws-login .
      - run: ./aws-login.exe version