name: release
on:
  push:
    tags:
      - v*
jobs:
  Release:
    name: Upload Release Asset
    runs-on: macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project 
        run: |
          go build -o aws-login .
          zip aws-login-${{ github.ref_name }} aws-login

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./aws-login-${{ github.ref_name }}.zip
          asset_name: aws-login-${{ github.ref_name }}.zip
          asset_content_type: application/zip