name: release
on:
  push:
    tags:
      - v*
jobs:
  Test:
    runs-on: macos-12
    steps:
      - name: Install go...
        uses: actions/setup-go@v3
        with:
          go-version: $GO_VERSION
      - name: Checkout repo...
        uses: actions/checkout@v3
      - name: Run Tests...
        run: |
          go test -v ./saml/
          go test -v ./auth/
  
  Test-Windows:
    runs-on: windows-latest
    steps:
      - name: Install go...
        uses: actions/setup-go@v3
        with:
          go-version: $GO_VERSION
      - name: Checkout repo...
        uses: actions/checkout@v3
      - name: Run Tests...
        run: |
          go test -v ./saml/
          go test -v ./auth/

  Release:
    name: Upload Release Asset
    runs-on: macos-12
    environment:
      name: ${{ github.ref_name }}
    needs:
      - Test
      - Test-Windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project - Mac
        run: |
          go build -o aws-login .
          zip aws-login-darwin-${{ github.ref_name }} aws-login
      
      - name: Build project - Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o aws-login.exe .
          zip aws-login-windows-${{ github.ref_name }} aws-login.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset - Mac
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./aws-login-darwin-${{ github.ref_name }}.zip
          asset_name: aws-login-darwin-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset - Windows
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./aws-login-windows-${{ github.ref_name }}.zip
          asset_name: aws-login-windows-${{ github.ref_name }}.zip
          asset_content_type: application/zip